### ISSUE TITLE
'Highlight reporter and assignee comments' feature is broken

### ISSUE THREAD

**Issue by Rik** [gkoberger/BugzillaJS#105]
No one reported it so it's probably not used a lot. But it should also be a simple fix because the DOM selections are not matching anymore.

**Comment by darkred** [comment]
I've noticed that the feature is broken (current version 3.5.0).

**Comment by yfdyh000** [comment]
@darkred it is works for me.

**Comment by darkred** [comment]
@yfdyh000 
I'm using Firefox 49.0.2.
Could you please provide a screenshot with the feature?
Because, e.g. in this bug I've reported: https://bugzilla.mozilla.org/show_bug.cgi?id=1227094
I can't spot any difference to my comment (comment 2) to e.g. comment 1: 
[2016-11-02_233857](https://cloud.githubusercontent.com/assets/723651/19948523/a24980be-a155-11e6-8e31-e5d2e6a87df0.jpg)

**Comment by yfdyh000** [comment]
@darkred In that bug, the reporter is comment 0:  Kostas(reporter) 0 years, 11 months ago.
![2016-11-03 05 43 01](https://cloud.githubusercontent.com/assets/1769875/19948626/7c76b702-a188-11e6-814c-7616faa1b320.png)

**Comment by darkred** [comment]
Yes, the reporter is me.
So, apart from my comment 0, shouldn't my following comments (comment 2) also be highlighted in green?

**Comment by yfdyh000** [comment]
I think the background color is highlighted for the hierarchy, not for the reporter identity.
![2016-11-03 05 49 02](https://cloud.githubusercontent.com/assets/1769875/19948758/4f73026e-a189-11e6-91d4-23d7ffd24bcb.png)

**Comment by darkred** [comment]
Ok, then the feature for me is not working at all, because as you may see in my screenshot there's no `(reporter)` next to my name in comments 0 or 2.

I also tested it in a clean FF 49.0.2 x64 profile too ( in win 10) with only BugzillaJS installed.

**Comment by yfdyh000** [comment]
That's it, only comment 0 is the green background. The Highlight feature just annotation like the "(reporter)", and turning off this feature does not affect the background colors.

Do you have checked this option in "BugzillaJS Preferences" (It's on the page)?

**Comment by darkred** [comment]
> Do you have checked this option in "BugzillaJS Preferences" (It's on the page)?

Yes, of course. (and, this option is enabled by default after installing BugzillaJS)
![2016-11-03_000430](https://cloud.githubusercontent.com/assets/723651/19949232/323ca5c2-a159-11e6-9ddf-abb857374175.jpg)

**Comment by yfdyh000** [comment]
Well, I have not encountered this problem so far. Fx50b11 x64 on Win10 x64.

**Comment by darkred** [comment]
[**@yfdyh000**](https://github.com/yfdyh000) commented on [Nov 3, 2016, 12:12 AM GMT+2](https://github.com/gkoberger/BugzillaJS/issues/105#issuecomment-258015429 "2016-11-02T22:12:18Z - Replied by Github Reply Comments"):
> Well, I have not encountered this problem so far. Fx50b11 x64 on Win10 x64.

I tested it with Firefox 49 x64 stable, 50 x64 stable, Nightly 52 x64  (on Win10 x64)
each time on a fresh profile with only BugzillaJS installed
and the feature doesn't work in either of them.

**Comment by darkred** [comment]
> Well, I have not encountered this problem so far. Fx50b11 x64 on Win10 x64.
@yfdyh000, as you may see, I tried all these FF versions,
and even tried previous (the 5 most recent) 
always with a clean FF profile and with BugzillaJS having its default settings.
and it doesn't work in any case.

It's very strange that it works for you. 
Could you please try it in a clean FF profile with only BugzillaJS?

**Comment by yfdyh000** [comment]
@darkred I still see it working with a new profile, Fx50.0 x64, BugzillaJS 3.5.0, after login (When not logged in, I can not find BugzillaJS), including Dusk or Mozilla skin.
with https://bugzilla.mozilla.org/show_bug.cgi?id=100002:
![2016-11-12 23 26 58](https://cloud.githubusercontent.com/assets/1769875/20238909/4e18e95c-a930-11e6-8d9a-f30df495215d.png)
![2016-11-12 23 27 05](https://cloud.githubusercontent.com/assets/1769875/20238910/4e21aa1a-a930-11e6-9b4f-772711e3cb9b.png)
with https://bugzilla.mozilla.org/show_bug.cgi?id=1227094:
![2016-11-12 23 28 24](https://cloud.githubusercontent.com/assets/1769875/20238908/4e10fcd8-a930-11e6-8180-c23c31020832.png)


Maybe your Bugzilla account settings affect it? Change an account and try again may be useful.

**Comment by darkred** [comment]
I checked all the settings in my Bugzilla account and are left to default (apart from the timezone).

And, I created another Bugzilla account as you suggested,
and tested it in both FF 49 and 50 with FF fresh profiles, having login with that new account,
and unfortunately it doesn't work.

**Comment by darkred** [comment]
Just for reference: I tried tweaking my Bugzilla account prefs (all of which had their default values).
and I found that the highlight feature works only if I set `Use experimental user interface ` to `on`.
But then. the relative timestamps are different than before:
e.g. for https://bugzilla.mozilla.org/show_bug.cgi?id=1227094 
comment 0 now is `a year ago` (instead of `0 years, 11 months ago`).

**Comment by darkred** [comment]
@yfdyh000 What if I uploaded the .htm of e.g. the last bugzilla link, would it be of any use to you? 
I mean, would it be useful to you to diff my .html saved file with an .htm that you'll save, in order to spot any differences in the HTML code that might be causing this issue?

I can't think of any other reason why it doesn't work for me.

**Comment by yfdyh000** [comment]
@darkred A good news: I have been able to reproduce the problem with a new account.
But bad news: It appears that this feature require you to have permission to edit the assignee field. https://developer.mozilla.org/en-US/docs/Mozilla/Bugzilla/What_to_do_and_what_not_to_do_in_Bugzilla#Getting.2FUpgrading_Bugzilla_privileges is enough.

Because there is no active maintainers, so I didn't study how to fix the problem on the source code.
And because https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017, if anyone interested to porting this extension to WebExtensions, I have a demo: https://github.com/yfdyh000/BugzillaJS/commits/WebExtension.

**Comment by darkred** [comment]
I have made this pull request https://github.com/gkoberger/BugzillaJS/pull/125.
I hope you agree with my suggested changes
