### ISSUE TITLE
BugzillaJS breaks formatting on some non-Bugzilla websites

### ISSUE THREAD

**Issue by cpeterso** [gkoberger/BugzillaJS#130]
STR:
1. Disable BugzillaJS.
2. Log into IRC Cloud, e.g. https://irccloud.mozilla.com/.
3. Enter command `/whois zzzzzzzzzzzzzzzzzzzzzzzzzz` (or any unused IRC nickname).
4. IRC Cloud shows a "No such channel/nick" dialog and it looks normal.
5. Enable BugzillaJS. You don't need to reload the IRC Cloud page or restart Firefox.
6. Enter command `/whois zzzzzzzzzzzzzzzzzzzzzzzzzz` again.

RESULT:
The "No such channel/nick" dialog is formatting is wrong. It is very wide and missing the white background.

**Comment by cpeterso** [comment]
Easier STR: Enabling BugzillaJS makes the text on http://www.sfgate.com/ very small.

**Comment by gregtatum** [comment]
It messes up arstechnica.com as well.

Expected result:
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/1588648/34428504-05ff6e1c-ec13-11e7-8b1b-b1b099635fd3.png">

Actual result:
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/1588648/34428498-f79c3710-ec12-11e7-8a87-af8e6a34607a.png">

**Comment by cpeterso** [comment]
And https://www.smartsheet.com/

**Comment by mnoorenberghe** [comment]
The reason for this is because although most JS rules tried to detect whether they were on a bug page, the CSS was just injected based on the `matches` rules which are quite inflexible and didn't support things like #129 to limit to specific domains at runtime. I had a workaround to inject the JS in the root of every domain with the JS deciding whether the page was relevant but forgot that the CSS was then inject to the root of every domain too. I've put another workaround in to limit to URLs that are more likely bugzilla installations. It's not perfect but I don't have time to implement #129 now.
